/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomCodeRouteImport } from './routes/room/$roomCode'
import { Route as ApiRoomsRoomCodeEventsRouteImport } from './routes/api/rooms/$roomCode/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomCodeRoute = RoomRoomCodeRouteImport.update({
  id: '/room/$roomCode',
  path: '/room/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomsRoomCodeEventsRoute = ApiRoomsRoomCodeEventsRouteImport.update({
  id: '/api/rooms/$roomCode/events',
  path: '/api/rooms/$roomCode/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/room/$roomCode': typeof RoomRoomCodeRoute
  '/api/rooms/$roomCode/events': typeof ApiRoomsRoomCodeEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/room/$roomCode': typeof RoomRoomCodeRoute
  '/api/rooms/$roomCode/events': typeof ApiRoomsRoomCodeEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/room/$roomCode': typeof RoomRoomCodeRoute
  '/api/rooms/$roomCode/events': typeof ApiRoomsRoomCodeEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/room/$roomCode' | '/api/rooms/$roomCode/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/room/$roomCode' | '/api/rooms/$roomCode/events'
  id: '__root__' | '/' | '/room/$roomCode' | '/api/rooms/$roomCode/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomRoomCodeRoute: typeof RoomRoomCodeRoute
  ApiRoomsRoomCodeEventsRoute: typeof ApiRoomsRoomCodeEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomCode': {
      id: '/room/$roomCode'
      path: '/room/$roomCode'
      fullPath: '/room/$roomCode'
      preLoaderRoute: typeof RoomRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rooms/$roomCode/events': {
      id: '/api/rooms/$roomCode/events'
      path: '/api/rooms/$roomCode/events'
      fullPath: '/api/rooms/$roomCode/events'
      preLoaderRoute: typeof ApiRoomsRoomCodeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomRoomCodeRoute: RoomRoomCodeRoute,
  ApiRoomsRoomCodeEventsRoute: ApiRoomsRoomCodeEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
